### ISSUE TITLE
Reorganize

### ISSUE THREAD

**Issue by feltnerm** [feltnerm/dotfiles#2]
Many years of cruft have been accumulated in this repo. I believe it is time to reorganize and rethink how this repository is organized and deployed.

This issue can serve as an "epic" to track multiple sub-issues.

Goals:
- [x] #3 _Platform agnostic_ - detect whether on Linux or OSX and perform appropriately. Provide common functions/hooks to check the current platform. Nice to have would be detecting different Linux distros and installing packages the appropriate way.
- [x] #4 _Shell agnostic_ - detect whether running in bash or zsh (or ...?) and perform appropriately. Provide common functions/hooks to check the current shell.
- [x] #5 _Initial setup/bootstrapping_ - Provide mechanism for bootstrapping a new system including installing required software, setting the correct options for the system, and setting correct options for installed software on the system.
- [x] #6 _General layout refactoring_ - make the repository easier to understand and reason about by namespacing things in logical folders (scripts, operating systems, etc.)
- [x] _Remove useless crap_
